import type { Metadata } from "next"
import { Nunito_Sans } from "next/font/google"
import "./globals.css"
import { Toaster } from "@/components/ui/sonner"
import { ModalProvider } from "@/providers/modal-provider"
import { QueryProvider } from "@/providers/query-provider"
import { SessionProvider } from "next-auth/react"
import { auth } from "@/auth"
const inter = Nunito_Sans({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const session = await auth()
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider session={session}>
          <QueryProvider>
            <Toaster richColors />
            <ModalProvider />
            {children}
          </QueryProvider>
        </SessionProvider>
      </body>
    </html>
  )
}
